batch_size: 8

generation: null 

logging:
  output_dir: "./results"
  results_path_template: null
  save_details: true
  push_to_hub: false
  push_to_tensorboard: false
  public_run: false
  results_org: null
  tensorboard_metric_prefix: "eval"

parallelism:
  dp: 4
  pp: 1
  tp: 1
  pp_engine: "1f1b"  # alternatives: "vanilla"

tasks:
  dataset_loading_processes: 8
  max_samples: null
  num_fewshot_seeds: null
  multichoice_continuations_start_space: null
  pairwise_tokenization: false
  custom_tasks: null
  tasks: "leaderboard|hellaswag|0|0,leaderboard|winogrande|0|0,helm|commonsenseqa|0|0,helm|piqa|0|0"
