checkpoints:
  checkpoint_interval: 100
  checkpoints_path: checkpoints/stage0_sft
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: checkpoints/stage0_context_cleaned_1
  save_initial_state: false
  save_final_state: true
  load_lr_scheduler: true
  load_optimizer: true

data_stages:
- data:
    dataset:
      hf_dataset_or_datasets: Pavankalyan/stage0_instruct_simple_split_merged
      hf_dataset_splits: train
      text_column_name: text
      dataset_processing_num_proc_per_process: 16
      dataset_overwrite_cache: true
      
    num_loading_workers: 16
    seed: 42
  name: Training Stage
  start_training_step: 1

general:
  benchmark_csv_path: benchmark_llama.csv
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: llama_150m_pretraining
  run: sft_stage0_%date_%jobid
  seed: 42
  step: null

lighteval: null

logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info

model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.01
    scaling_method: NUM_LAYERS
  make_vocab_size_divisible_by: 128
  model_config:
    bos_token_id: 50256
    eos_token_id: 50256
    hidden_act: silu
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 2048
    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 12
    num_hidden_layers: 12
    num_key_value_heads: 12
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    rope_interleaved: false
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 50259  # Rounded up to be divisible by 128
    _attn_implementation: flash_attention_2
    attention_bias: false
    z_loss_enabled: false
    z_loss_coefficient: 0.0001

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 1.0e-4
    lr_decay_starting_step: null
    lr_decay_steps: 5801  # 90% of total steps for cosine decay
    lr_decay_style: cosine
    lr_warmup_steps: 644 # ~10% of total steps
    lr_warmup_style: linear
    min_decay_lr: 1.0e-5  # 10% of peak LR
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  weight_decay_exclude_named_params: []
  zero_stage: 1

parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
  recompute_layer: false
  moe_layer_recompute: false
  context_parallel_size: 1

profiler:
  profiler_export_path: ./tb_logs/150m_training/
  wait: 5
  warmup: 5
  active: 5
  repeat: 1
  skip_first: 10
  record_shapes: false
  profile_memory: false
  with_stack: true
  export_chrome_trace: false

tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: Pavankalyan/TinyStoriesInstruct-tokenizer
  tokenizer_revision: null

tokens:
  batch_accumulation_per_replica: 8
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 32
  sequence_length: 2048
  train_steps: 6446  # 216 + 6230 = 4 epochs * (1225312256 / (4 GPUs * 8 micro_batch * 16 accum * 2048 seq_len))
  val_check_interval: -1

metrics_logging: null
s3_upload: null

# Calculated for exactly 2 epochs: 226756608 / (4 * 32 * 8 * 2048) = 108 steps per epoch