checkpoints:
  checkpoint_interval: 1000 #
  checkpoints_path: checkpoints/stages_1_mix
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder: /datadrive/pavan/CurLL/data/Experiments/stages_1_mix
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
# - data:
#     dataset:
#       dataset_folder: /datadrive/pavan/CurLL/data/tinystories/val_orig_tokenizer
#     num_loading_workers: 1
#     seed: 42
#   name: val
#   start_training_step: 2
general:
  benchmark_csv_path: benchmark_llama.csv
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: tinystories
  run: stages_1_mix
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 50256
    eos_token_id: 50256
    hidden_act: gelu_new
    hidden_size: 576
    initializer_range: 0.02
    intermediate_size: 1536 # figure this out for 33M 
    is_llama_config: true
    max_position_embeddings: 8192
    num_attention_heads: 9
    num_hidden_layers: 30
    num_key_value_heads: 9
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 50259
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0005
    lr_decay_starting_step: 0
    lr_decay_steps: 2000
    lr_decay_style: cosine
    lr_warmup_steps: 150
    lr_warmup_style: linear
    min_decay_lr: 1.0e-06
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.98
    adam_eps: 1.0e-06
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 0
parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
profiler:
  profiler_export_path: ./tb_logs/fix/
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: Pavankalyan/TinyStoriesInstruct-tokenizer
  tokenizer_revision: null
tokens:
  micro_batch_size: 32                # 
  batch_accumulation_per_replica: 4   # effective batch size = 32 × 4 × 4 = 512
  sequence_length: 2048               # batch size in tokens = 1024 x 2048 = 2097152
  train_steps: 2000                    # Approximately 2 epochs (2093560664x2 / 2097152 = 1996)
  val_check_interval: 2
  limit_test_batches: 0
  limit_val_batches: 64
  validation_steps: 5

